[package]
org = "wso2healthcare"
name = "bal_cerner_project"
version = "0.1.0"
export = ["bal_cerner_project"]
distribution = "2201.1.2"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Cerner"]

[build-options]
observabilityIncluded = true
